#include "ai.h"

#include "../format/t3do.h"
#include "../model/model.h"
#include "../texture/write.h"
#include "../util/io.h"
#include "../util/log.h"
#include "../util/types.h"
#include "../writer/debug.h"
#include "../writer/export.h"

#include <algorithm>
#include <array>
#include <charconv>
#include <cmath>
#include <format>
#include <ranges>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace nova3di::composite::ai {

	namespace {

		namespace nlog    = nova3di::util::log;
		namespace io      = nova3di::util::io;
		namespace texture = nova3di::texture;
		namespace t3do    = nova3di::format::t3do;

		//============================================================================
		// Parsed .AI structs
		//============================================================================

		// AF3: leading int + >G/D/S/N/R/B + >IDOV + >DATA + >LEAF
		// C3G: shared >g/>d/>s + "<<" separator + 4-char plot routine lines
		enum class Version {
			Af3,
			C3g,
		};

		// AI section names
		enum class Section {
			None,
			Env,        // af3: one env's parts list  |  c3g: env+parts zone (before <<)
			Idov,       // af3
			Leaf,       // af3
			Routines,   // c3g: plot + move routine (after <<)
			Metadata    // c3g: trailing ignored fields
		};
		
		struct Environment {
			std::string tag; // "G", "D", "S", "N", "R", "B", "LEAF" (AF3) or "G", "D", "S" (C3G)
			std::vector<std::string> parts; // 3do files
		};

		// C3G Plot Routine: "helo,0,15" parses to {"helo", 0, 15}.
		struct PlotRoutine {
			std::string name;      // char type name, e.g. "helo"
			int         base_part;
			int         cutoff;    // metres
		};

		struct ParsedAi {
			Version                   version = Version::Af3;
			int                       type = 0;      // AF3
			std::vector<Environment>  envs;          // AF3 + C3G (shared)
			std::string               idov;          // AF3
			int                       leaf = 0;      // AF3
			std::vector<PlotRoutine>  plot_routines; // C3G
		};

		struct Part {
			std::string     name;
			t3do::Parsed3do data;
			bool            active = false;
		};

		struct AttachedPart {
			size_t             part_idx;
			std::array<i32, 3> offset;
			bool               mirror_x  = false;  // X-only flip (AF3 mirror-pair canopies)
			bool               rot_y_180 = false;  // 180-Y rotation (C3G tire/wtnk wheel mirror)
		};

		struct Attachment {
			i8  slot        = 0;
			i8  parent_slot = 0;
			i8  mesh_idx    = 0;
			i8  mirror_x    = 0;
			i8  rot_y_180   = 0;
		};

		struct Assembly {
			u8          type;       // AF3: 1-64
			const char* name;       // C3G: type name
			u8          count;
			std::array<Attachment, 24> attachments;
		};

		// AF3 .AI per-type assembly table. Auto-generated by af3_extract_positioning.py
		// DO NOT edit by hand. Per-type source addresses and per-type notes in 3DO_AI_AF3.md
		constexpr Assembly af3_assemblies[] = {
			{ 1, nullptr, 7, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {4,1,7,0,0}, {5,1,5,0,0}, {6,5,0,0,0}, {7,1,5,0,0} }} },
			{ 2, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,-1,-1,0,0} }} },
			{ 3, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,-1,-1,0,0} }} },
			{ 4, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,-1,-1,0,0} }} },
			{ 5, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 6, nullptr, 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,-1,-2,0,0}, {3,0,1,0,0}, {4,-1,-2,0,0}, {5,-1,-1,0,0} }} },
			{ 8, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,1,1,0,0} }} },
			{ 9, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 10, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 11, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 14, nullptr, 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,-1,-2,0,0}, {3,0,1,0,0}, {4,-1,-2,0,0}, {5,-1,-1,0,0} }} },
			{ 15, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 16, nullptr, 5, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,0,0,0,0}, {2,0,1,1,0}, {3,0,3,0,0} }} },
			{ 17, nullptr, 5, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,1,1,0,0}, {4,-1,-1,0,0} }} },
			{ 18, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 19, nullptr, 2, {{ {0,-1,-1,0,0}, {1,0,0,0,0} }} },
			{ 20, nullptr, 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,-1,-1,0,0}, {4,0,3,0,0}, {4,0,4,1,0} }} },
			{ 21, nullptr, 2, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0} }} },
			{ 22, nullptr, 4, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,0,0,0,0}, {2,0,1,1,0} }} },
			{ 24, nullptr, 2, {{ {0,-1,-1,0,0}, {3,-1,-1,0,0} }} },
			{ 27, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 28, nullptr, 2, {{ {0,-1,-1,0,0}, {1,0,-3,0,0} }} },
			{ 29, nullptr, 2, {{ {0,-1,-1,0,0}, {1,0,-3,0,0} }} },
			{ 30, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 31, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 33, nullptr, 2, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0} }} },
			{ 34, nullptr, 2, {{ {0,-1,-1,0,0}, {2,-1,-1,0,0} }} },
			{ 35, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 36, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 38, nullptr, 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,-1,-1,0,0}, {4,0,3,0,0}, {4,0,4,1,0} }} },
			{ 45, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 46, nullptr, 2, {{ {0,-1,-1,0,0}, {1,0,0,0,0} }} },
			{ 48, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 49, nullptr, 2, {{ {0,-1,-1,0,0}, {1,0,0,0,0} }} },
			{ 50, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 52, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,1,0,0}, {1,0,0,0,0}, {2,0,2,0,0} }} },
			{ 53, nullptr, 4, {{ {0,-1,-1,0,0}, {1,0,1,0,0}, {1,0,0,0,0}, {2,0,2,0,0} }} },
			{ 54, nullptr, 3, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0} }} },
			{ 55, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 57, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 59, nullptr, 4, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,0,0,0,0}, {2,0,1,1,0} }} },
			{ 60, nullptr, 15, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,1,1,0,0}, {5,3,0,0,0}, {7,5,0,0,0}, {4,1,2,0,0}, {6,4,0,0,0}, {8,6,0,0,0}, {9,0,1,0,0}, {11,9,0,0,0}, {13,11,0,0,0}, {10,0,2,0,0}, {12,10,0,0,0}, {14,12,0,0,0} }} },
			{ 61, nullptr, 1, {{ {0,-1,-1,0,0} }} },
			{ 62, nullptr, 2, {{ {0,-1,-1,0,0}, {8,-1,-1,0,0} }} },
			{ 63, nullptr, 2, {{ {0,-1,-1,0,0}, {8,-1,-1,0,0} }} },
			{ 64, nullptr, 1, {{ {0,-1,-1,0,0} }} },
		};

		// C3G .AI plot-routine assembly table
		// rot_y_180=1 mirrors a part's X+Z (180-Y rotation), used by tire/wtnk for
		// the right-side wheel which shares its mesh with the left.
		constexpr Assembly c3g_assemblies[] = {
			// Single-part / no-op routines
			{ 0, "1prt", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "1pr2", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "face", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "airp", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "flr1", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "glue", 1, {{ {0,-1,-1,0,0} }} },
			{ 0, "edit", 0, {{}} },
			{ 0, "null", 0, {{}} },
			{ 0, "ndot", 0, {{}} },
			{ 0, "mdot", 0, {{}} },
			{ 0, "fdot", 0, {{}} },

			// Two-part assemblies
			{ 0, "2prt", 2, {{ {0,-1,-1,0,0}, {1,0,0,0,0} }} },
			{ 0, "2psc", 2, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0} }} },
			{ 0, "prop", 2, {{ {0,-1,-1,0,0}, {1,0,0,0,0} }} },
			{ 0, "chi2", 2, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0} }} },

			// Helicopters
			{ 0, "helo", 5, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,-1,-1,0,0}, {3,0,2,0,0}, {4,0,2,0,0} }} },
			{ 0, "wolf", 5, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,-1,-1,0,0}, {3,-1,-1,0,0}, {4,-1,-1,0,0} }} },
			{ 0, "chin", 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,0,0,0,0}, {1,0,1,0,0}, {2,0,1,0,0}, {3,0,2,0,0} }} },

			// Tanks / wheeled / tracked vehicles
			{ 0, "tank", 4, {{ {3,-1,-1,0,0}, {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0} }} },
			{ 0, "tire", 4, {{ {1,-1,-1,0,0}, {0,-1,-1,0,0}, {2,0,0,0,0}, {2,0,1,0,1} }} },
			{ 0, "wtnk", 6, {{ {3,-1,-1,0,0}, {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {4,0,3,0,0}, {4,0,4,0,1} }} },
			{ 0, "2sa6", 5, {{ {4,-1,-1,0,0}, {0,-1,-1,0,0}, {1,0,0,0,0}, {3,1,1,0,0}, {2,1,0,0,0} }} }, 
			{ 0, "pump", 5, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {4,1,1,0,0}, {3,1,0,0,0}, {2,0,1,0,0} }} }, 

			// Naval
			{ 0, "nanu", 5, {{ {4,-1,-1,0,0}, {0,-1,-1,0,0}, {3,0,3,0,0}, {1,0,0,0,0}, {2,1,0,0,0} }} },
			{ 0, "shal", 6, {{ {5,-1,-1,0,0}, {0,-1,-1,0,0}, {4,0,2,0,0}, {3,0,1,0,0}, {1,0,0,0,0}, {2,1,0,0,0} }} },

			// Misc / decoration
			{ 0, "sock", 4, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,1,0,0,0}, {3,2,0,0,0} }} },

			// Trees 
			{ 0, "tre5", 6, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,0,1,0,0}, {3,0,2,0,0}, {4,0,3,0,0}, {5,0,4,0,0} }} },
			{ 0, "tre6", 7, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,0,1,0,0}, {3,0,2,0,0}, {4,0,3,0,0}, {5,0,4,0,0}, {6,0,5,0,0} }} },
			{ 0, "tr17", 18, {{ {0,-1,-1,0,0}, {1,0,0,0,0}, {2,0,1,0,0}, {3,0,2,0,0}, {4,0,3,0,0}, {5,0,4,0,0}, {6,0,5,0,0}, {7,0,6,0,0}, {8,0,7,0,0}, {9,0,8,0,0}, {10,0,9,0,0}, {11,0,10,0,0}, {12,0,11,0,0}, {13,0,12,0,0}, {14,0,13,0,0}, {15,0,14,0,0}, {16,0,15,0,0}, {17,0,10,0,0} }} },

			// `coma` (player heli), best guess
			{ 0, "coma", 17, {{ {0,-1,-1,0,0}, {1,-1,-1,0,0}, {2,-1,-1,0,0}, {3,-1,-1,0,0}, {4,-1,-1,0,0}, {5,-1,-1,0,0}, {6,-1,-1,0,0}, {7,-1,-1,0,0}, {8,-1,-1,0,0}, {9,-1,-1,0,0}, {10,-1,-1,0,0}, {11,-1,-1,0,0}, {12,-1,-1,0,0}, {13,-1,-1,0,0}, {14,-1,-1,0,0}, {15,-1,-1,0,0}, {16,-1,-1,0,0} }} },
		};

		//============================================================================
		// Find an assembly in the AF3 table by type byte
		//============================================================================
		const Assembly* find_af3_assembly(int type) {
			for(const auto& assembly : af3_assemblies) {
				if((int)assembly.type == type) 
					return &assembly;
			}
			return nullptr;
		}

		//============================================================================
		// Find an assembly in the C3G table by type name
		//============================================================================
		const Assembly* find_c3g_assembly(std::string_view name) {
			for(const auto& assembly : c3g_assemblies) {
				if(assembly.name && name == assembly.name) 
					return &assembly;
			}
			return nullptr;
		}

		//============================================================================
		// Pick the highest-available LOD variant for each AI part reference
		// Order: H > M > L
		//============================================================================
		std::string resolve_lod(const std::string& filename, char new_lod) {

			std::string stem = io::strip_ext(filename);
			std::string ext  = filename.substr(stem.size());  // dot + ext, or "" if none

			size_t underscore_pos = stem.find_last_of('_');

			if(underscore_pos == std::string::npos || underscore_pos + 1 >= stem.size())
				return filename;

			char marker = stem[underscore_pos + 1];

			if(!((marker >= 'a' && marker <= 'z') || (marker >= 'A' && marker <= 'Z')))
				return filename;

			return stem.substr(0, underscore_pos + 1) + new_lod + stem.substr(underscore_pos + 2) + ext;
		}

		//============================================================================
		// Resolve each part's lod-ref (e.g. "wheel_L.3do") to an actual file on disk,
		// with preference order H > M > L
		//============================================================================
		std::string resolve_part(const std::string& input_dir, const std::string& ai_ref) {

			std::vector<std::string> candidates;
			candidates.push_back(ai_ref);

			for(char lod : {'H', 'M', 'L'}) {
				std::string lod_sub = resolve_lod(ai_ref, lod);

				if(lod_sub != ai_ref)
					candidates.push_back(lod_sub);
					
			}

			// Collect every candidate that exists on disk, keyed by its LOD
			// letter (uppercased, '?' if there's no _<letter> marker). First
			// resolution for each key wins since resolve_lod only produces
			// one candidate per H/M/L.
			std::map<char, std::string> found;

			for(const auto& candidate : candidates) {

				std::string disk = io::resolve_filename(input_dir, candidate);

				if(disk.empty())
					continue;

				std::string stem = io::strip_ext(disk);
				size_t underscore_pos = stem.find_last_of('_');
				char lod = (underscore_pos != std::string::npos && underscore_pos + 1 < stem.size()) ? stem[underscore_pos + 1] : '?';

				if(lod >= 'a' && lod <= 'z')
					lod = (char)(lod - 32);

				found.emplace(lod, disk);
			}

			if(found.empty())
				return "";

			for(char lod : {'H', 'M', 'L'}) {
				if(auto it = found.find(lod); it != found.end())
					return it->second;
			}

			return found.begin()->second;
		}

		//============================================================================
		// Load each .3DO referenced by the .AI
		//============================================================================
		std::vector<Part> load_parts(
			const std::string& input_dir,
			const std::vector<std::string>& ai_parts,
			const std::string& tag_label,
			const model::ConvertOptions& opts
		) {

			std::vector<Part> parts;
			parts.reserve(ai_parts.size());

			auto push_placeholder = [&](const std::string& stem) {
				Part part;
				part.name = stem;
				parts.push_back(std::move(part));
			};

			for(const auto& ai_ref : ai_parts) {

				std::string resolved = resolve_part(input_dir, ai_ref);

				if(resolved.empty()) {

					nlog::warn("[%s] part not found: %s (tried _H/_M/_L substitution)", tag_label.c_str(), ai_ref.c_str());

					push_placeholder(io::strip_ext(ai_ref));

					continue;
				}

				std::string part_path = input_dir + "\\" + resolved;
				auto buf_opt = io::read_file(part_path);

				if(!buf_opt) {
					nlog::warn("[%s] cannot open %s", tag_label.c_str(), resolved.c_str());
					push_placeholder(io::strip_ext(resolved));
					continue;
				}
				std::vector<u8>& buf = *buf_opt;

				Part part;
				part.name = io::strip_ext(resolved);

				if(!t3do::parse_3do(buf, {}, input_dir, opts, part.data)) {
					nlog::warn("[%s] not a valid .3DO: %s", tag_label.c_str(), resolved.c_str());
					push_placeholder(io::strip_ext(resolved));
					continue;
				}

				if(part.data.triangles.empty()) {
					nlog::step("[%s] %s: empty model, skipped\n", tag_label.c_str(), resolved.c_str());
					push_placeholder(io::strip_ext(resolved));
					continue;
				}

				part.active = true;
				parts.push_back(std::move(part));

			}

			return parts;
		}

		//============================================================================
		// Appends zero or more AttachedParts into "attached" and records the first
		// offset per slot in part_offset/exists for child attachments.
		// mesh_idx == -3 drives a canopy repeat
		//============================================================================
		void apply_attachment(
			const Attachment& att,
			const std::vector<Part>& parts,
			i64 body_diag,
			std::vector<std::array<i32,3>>& part_offset,
			std::vector<bool>& part_exists,
			std::vector<AttachedPart>& attached
		) {

			if(att.slot < 0 || (size_t)att.slot >= parts.size())
				return;

			if(att.mesh_idx == -2)
				return;

			auto is_sentinel = [body_diag](i32 v) {
				return (i64)v > body_diag || (i64)v < -body_diag;
			};

			auto get_parent_mesh = [&parts](int source) -> const std::vector<std::array<i32,3>>* {
				if(source < 0 || (size_t)source >= parts.size())
					return nullptr;
				return &parts[source].data.mesh_entries;
			};

			auto add_attached = [&](size_t slot, std::array<i32,3> base, bool mirror, bool rot_y_180) {
				attached.push_back({slot, base, mirror, rot_y_180});
				if(!part_exists[slot]) {
					part_offset[slot] = base;
					part_exists[slot] = true;
				}
			};

			std::array<i32,3> origin = {0,0,0};

			if(att.parent_slot >= 0 && (size_t)att.parent_slot < parts.size() && part_exists[att.parent_slot])
				origin = part_offset[att.parent_slot];

			int  source     = (att.parent_slot >= 0) ? att.parent_slot : 0;
			bool mirror     = att.mirror_x  != 0;
			bool rot_y_180  = att.rot_y_180 != 0;

			if(att.mesh_idx == -3) {

				auto* mesh = get_parent_mesh(source);

				if(!mesh)
					return;

				for(const auto& entry : *mesh) {

					if(is_sentinel(entry[0]) || is_sentinel(entry[1]) || is_sentinel(entry[2]))
						continue;

					std::array<i32,3> base = {
						origin[0] + entry[0],
						origin[1] + entry[1],
						origin[2] + entry[2]
					};

					add_attached((size_t)att.slot, base, mirror, rot_y_180);
				}
				return;
			}

			std::array<i32,3> base = origin;

			if(att.mesh_idx >= 0) {

				if(auto* mesh = get_parent_mesh(source); mesh && (size_t)att.mesh_idx < mesh->size()) {

					const auto& entry = (*mesh)[att.mesh_idx];

					if(!(is_sentinel(entry[0]) || is_sentinel(entry[1]) || is_sentinel(entry[2]))) {
						base[0] += entry[0];
						base[1] += entry[1];
						base[2] += entry[2];
					}
				}
			}

			add_attached((size_t)att.slot, base, mirror, rot_y_180);
		}

		//============================================================================
		// Some models have parts absurdly far from the body. Anything outside
		// [-diag, diag] is skipped
		//============================================================================
		i64 resolve_body_diag(const std::vector<Part>& parts) {

			constexpr i64 MIN_BODY_DIAG = 2'000'000;

			if(parts.empty() || parts[0].data.vertices.empty())
				return MIN_BODY_DIAG;

			const auto& body_vertices = parts[0].data.vertices;

			i64 body_min_x = body_vertices[0].x, body_max_x = body_vertices[0].x;
			i64 body_min_y = body_vertices[0].y, body_max_y = body_vertices[0].y;
			i64 body_min_z = body_vertices[0].z, body_max_z = body_vertices[0].z;

			for(const auto& vert : body_vertices) {
				body_min_x = std::min<i64>(body_min_x, vert.x);
				body_max_x = std::max<i64>(body_max_x, vert.x);
				body_min_y = std::min<i64>(body_min_y, vert.y);
				body_max_y = std::max<i64>(body_max_y, vert.y);
				body_min_z = std::min<i64>(body_min_z, vert.z);
				body_max_z = std::max<i64>(body_max_z, vert.z);
			}

			i64 dx = body_max_x - body_min_x;
			i64 dy = body_max_y - body_min_y;
			i64 dz = body_max_z - body_min_z;

			i64 body_diag = (i64)std::sqrt((double)(dx*dx + dy*dy + dz*dz));

			return std::max(body_diag, MIN_BODY_DIAG);
		}

		//============================================================================
		// AF3: derive per-attachment world-space offsets using af3_assemblies when
		// available, else a simple fallback that attaches each non-flat part i to
		// body.mesh_entries[i-1]. X = destroyed version, skips the table
		//============================================================================
		std::vector<AttachedPart> resolve_attached_parts_af3(
			const std::vector<Part>& parts,
			int ai_type,
			bool x_variant
		) {

			std::vector<AttachedPart> attached;
			std::vector<std::array<i32, 3>> part_offset(parts.size(), {0,0,0});
			std::vector<bool> part_exists(parts.size(), false);

			const Assembly* assembly = x_variant ? nullptr : find_af3_assembly(ai_type);

			i64 body_diag = resolve_body_diag(parts);

			if(assembly) {
				for(u8 k = 0; k < assembly->count; ++k)
					apply_attachment(assembly->attachments[k], parts, body_diag,
					                 part_offset, part_exists, attached);
			} else {

				// Fallback for types not covered by af3_assemblies. Body at origin,
				// each sub-part at body.mesh_entries[i-1]. Does not cover all cases.
				attached.push_back({0, {0,0,0}});
				if(parts.size() >= 2) {

					const auto& body_meshes = parts[0].data.mesh_entries;

					for(size_t i = 1; i < parts.size(); ++i) {

						std::array<i32,3> off = {0,0,0};
						size_t entry_idx = i - 1;

						if(entry_idx < body_meshes.size())
							off = body_meshes[entry_idx];

						attached.push_back({i, off});
					}

				}

			}

			return attached;
		}

		//============================================================================
		// C3G: the attachment's slot/parent_slot are shifted by the routeings's
		// base_part to address the env's parts vector.
		//============================================================================
		std::vector<AttachedPart> resolve_attached_parts_c3g(
			const std::vector<Part>& parts,
			const PlotRoutine& routine
		) {

			std::vector<AttachedPart> attached;
			std::vector<std::array<i32, 3>> part_offset(parts.size(), {0,0,0});
			std::vector<bool> part_exists(parts.size(), false);

			const Assembly* assembly = find_c3g_assembly(routine.name);

			if(!assembly) {
				nlog::warn("unknown plot routine '%s' (no row in c3g_assemblies)", routine.name.c_str());
				return attached;
			}

			i64 body_diag = resolve_body_diag(parts);

			for(u8 k = 0; k < assembly->count; ++k) {
				Attachment att = assembly->attachments[k];
				att.slot += (i8)routine.base_part;
				if(att.parent_slot >= 0)
					att.parent_slot += (i8)routine.base_part;
				apply_attachment(att, parts, body_diag, part_offset, part_exists, attached);
			}

			return attached;
		}

		struct EnvTextures {
			std::map<std::string, std::string> tex_filename;
			int found   = 0;
			int missing = 0;
		};

		EnvTextures get_env_textures(
			const std::vector<Part>& parts,
			const std::string& out_dir,
			const model::ConvertOptions& opts
		) {

			std::vector<texture::Image> textures;

			for(const auto& part : parts) {
				for(const auto& img : part.data.resolved_textures)
					textures.push_back(img);
			}

			auto write_result = texture::write_all(out_dir, std::span<const texture::Image>{textures}, opts.raw);

			EnvTextures result;
			result.found   = write_result.found;
			result.missing = write_result.missing;

			for(size_t i = 0; i < textures.size(); ++i)
				result.tex_filename[textures[i].name] = write_result.filenames[i];

			return result;
		}

		//============================================================================
		// Opacity material-name suffix; empty for fully opaque
		//============================================================================
		std::string opacity_suffix(float opacity) {
			if(opacity == 1.0f)
				return "";
			return "_op" + std::to_string((int)(opacity * 100));
		}

		//============================================================================
		// Flat-color material name. Opacity sub-key keeps same-rgb unnamed
		// textures with different opacities from collapsing into one material
		//============================================================================
		std::string flat_mat_name(const t3do::Texture& tex, float opacity) {
			return std::format("flat_{}_{}_{}{}", tex.r, tex.g, tex.b, opacity_suffix(opacity));
		}

		//============================================================================
		// Material name from a (3DO entry, spec) pair. Textured: base name +
		// mode_suffix [+ opacity suffix]. Flat: flat_R_G_B [+ opacity suffix].
		//============================================================================
		std::string mat_name(const t3do::Texture& tex, const texture::TextureSpec& spec) {

			if(tex.name.empty())
				return flat_mat_name(tex, spec.opacity);

			std::string name = io::strip_ext(tex.name);
			name += std::string(texture::mode_suffix(spec.mode));
			name += opacity_suffix(spec.opacity);

			return name;
		}

		//============================================================================
		// Build a single Mesh for one attached part at its world-space offset
		//============================================================================
		model::Mesh build_attached_part(
			const Part& part,
			const AttachedPart& ap,
			int copy_num,
			const std::map<std::string, int>& mat_index,
			int default_mat_idx
		) {

			model::Mesh mesh;

			if(copy_num == 1)
				mesh.group_name = part.name;
			else
				mesh.group_name = part.name + "_" + std::to_string(copy_num);

			i32 off_x = ap.offset[0];
			i32 off_y = ap.offset[1];
			i32 off_z = ap.offset[2];
			bool mirror    = ap.mirror_x;
			bool rot_y_180 = ap.rot_y_180;

			mesh.positions.reserve(part.data.vertices.size());
			mesh.uvs.reserve(part.data.vertices.size());
			mesh.normals.reserve(part.data.normals.size());

			for(const auto& vert : part.data.vertices) {
				i32 vx = mirror    ? -vert.x : vert.x;
				i32 vy = vert.y;
				i32 vz = vert.z;

				// 180-Y rotation flips X and Z (C3G tire/wtnk wheel mirror)
				if(rot_y_180) { 
					vx = -vx; 
					vy = -vy; 
				}
				
				// Y/Z swap: (-x, z, -y)
				mesh.positions.push_back({
					(double)-(vx + off_x), (double)(vz + off_z), (double)-(vy + off_y)
				});

				mesh.uvs.push_back({
					(double)vert.u, 1.0 - (double)vert.v
				});
			}

			for(const auto& norm : part.data.normals) {
				float nx = mirror    ? -norm.nx : norm.nx;
				float ny = norm.ny;
				float nz = norm.nz;

				if(rot_y_180) { 
					nx = -nx; 
					ny = -ny; 
				}

				mesh.normals.push_back({(double)-nx, (double)nz, (double)-ny});
			}

			for(size_t tri_idx = 0; tri_idx < part.data.triangles.size(); ++tri_idx) {

				const auto& tri = part.data.triangles[tri_idx];

				if(tri_idx < part.data.ex_geometry.size() && part.data.ex_geometry[tri_idx])
					continue;

				u32 face_tex_idx = (tri.tex_idx < part.data.textures.size())
							? tri.tex_idx
							: (u32)part.data.textures.size();

				int mat_idx = -1;

				if(face_tex_idx < part.data.textures.size()) {

					const t3do::Texture& tex = part.data.textures[face_tex_idx];
					const texture::TextureSpec& spec = (face_tex_idx < part.data.specs.size())
						? part.data.specs[face_tex_idx]
						: texture::TextureSpec{};
					std::string mat = mat_name(tex, spec);

					auto mat_it = mat_index.find(io::to_lower(mat));

					if(mat_it != mat_index.end())
						mat_idx = mat_it->second;
				}

				if(mat_idx < 0) {
					if(default_mat_idx >= 0)
						mat_idx = default_mat_idx;
					else
						continue;
				}

				model::Face face = {};

				if(mirror) {
					// Mirror flips winding. swap v[1] and v[2] to preserve front-facing
					face.v[0] = {(i32)tri.vi[0], (i32)tri.ni[0], (i32)tri.vi[0]};
					face.v[1] = {(i32)tri.vi[2], (i32)tri.ni[2], (i32)tri.vi[2]};
					face.v[2] = {(i32)tri.vi[1], (i32)tri.ni[1], (i32)tri.vi[1]};
				} else {
					face.v[0] = {(i32)tri.vi[0], (i32)tri.ni[0], (i32)tri.vi[0]};
					face.v[1] = {(i32)tri.vi[1], (i32)tri.ni[1], (i32)tri.vi[1]};
					face.v[2] = {(i32)tri.vi[2], (i32)tri.ni[2], (i32)tri.vi[2]};
				}

				face.material = (u32)mat_idx;
				mesh.faces.push_back(face);
			}

			return mesh;
		}

		//============================================================================
		// Build the Model for one env (G,D,S,N etc.)
		//============================================================================
		void build_model(
			const std::vector<Part>& parts,
			const std::vector<AttachedPart>& attached,
			const std::map<std::string, std::string>& tex_filename,
			const std::string& model_stem,
			const std::string& tag_label,
			model::Model& model
		) {

			model.source_name = std::format("{}.AI ({}, {} parts)", model_stem, tag_label, parts.size());
			model.format_tag  = "ai";

			std::map<std::string, int> mat_index;  // name_lc -> index

			auto add_material = [&](size_t part_idx, size_t tex_idx) -> int {

				const auto& tex  = parts[part_idx].data.textures[tex_idx];
				const auto& spec = parts[part_idx].data.specs[tex_idx];

				bool        is_flat = tex.name.empty();
				std::string name    = mat_name(tex, spec);
				std::string key     = io::to_lower(name);

				auto it = mat_index.find(key);

				if(it != mat_index.end())
					return it->second;

				int idx = (int)model.materials.size();

				model::Material mat;
				mat.name    = name;
				mat.opacity = spec.opacity;

				if(is_flat) {

					mat.color[0] = tex.r / 255.0f;
					mat.color[1] = tex.g / 255.0f;
					mat.color[2] = tex.b / 255.0f;

				} else {
					mat.color[0] = mat.color[1] = mat.color[2] = 0.8f;

					std::string tex_key = io::strip_ext(tex.name) + std::string(texture::mode_suffix(spec.mode));
					auto filename_it = tex_filename.find(tex_key);

					if(filename_it != tex_filename.end() && !filename_it->second.empty()) {
						mat.texture = filename_it->second;

						if(io::extension(filename_it->second) == ".tga")
							mat.alpha = filename_it->second;

					}
				}

				model.materials.push_back(mat);
				mat_index[key] = idx;

				return idx;
			};

			for(size_t part_idx = 0; part_idx < parts.size(); ++part_idx) {
				const auto& part = parts[part_idx];

				for(size_t tex_idx = 0; tex_idx < part.data.textures.size(); ++tex_idx) {

					if(tex_idx < part.data.ex_textures.size() && part.data.ex_textures[tex_idx])
						continue;

					add_material(part_idx, tex_idx);
				}
			}

			int default_mat_idx = -1;
			bool need_default = std::ranges::any_of(attached, [&](const auto& ap) {

				const auto& part_data = parts[ap.part_idx].data;

				return std::ranges::any_of(part_data.triangles, [&](const auto& tri) {
					return tri.tex_idx >= part_data.textures.size();
				});

			});

			if(need_default) {
				model::Material default_mat;
				default_mat.name = "default";
				default_mat.color[0] = default_mat.color[1] = default_mat.color[2] = 0.8f;
				default_mat_idx = (int)model.materials.size();
				model.materials.push_back(default_mat);
			}

			std::vector<int> part_copy_count(parts.size(), 0);

			for(const auto& ap : attached) {
				int copy_num = ++part_copy_count[ap.part_idx];

				model.meshes.push_back(
					build_attached_part(
						parts[ap.part_idx], ap, copy_num,
						mat_index, default_mat_idx
					)
				);

			}
		}

		//============================================================================
		// PartFrame at each attached part's placement for debugging visualization
		//============================================================================
		std::vector<writer::debug::PartFrame> build_part_frames(
			std::span<const Part> parts,
			std::span<const AttachedPart> attached
		) {

			std::vector<writer::debug::PartFrame> frames;
			frames.reserve(attached.size());

			for(size_t i = 0; i < attached.size(); ++i) {
				const AttachedPart& ap = attached[i];
				const std::string& part_name = parts[ap.part_idx].name;

				writer::debug::PartFrame f;
				const char* tag_suffix =
					ap.rot_y_180 ? "_roty180" :
					ap.mirror_x  ? "_mirror"  : "";
				f.name = std::format("{}_{}{}", part_name, i, tag_suffix);

				// OBJ-space origin matches the (-(x+off), z+off, -(y+off))
				// transform applied in build_attached_part.
				f.origin[0] = -(double)ap.offset[0];
				f.origin[1] =  (double)ap.offset[2];
				f.origin[2] = -(double)ap.offset[1];

				double sx = (ap.mirror_x || ap.rot_y_180) ? -1.0 : 1.0;
				double sz = ap.rot_y_180                  ? -1.0 : 1.0;
				f.basis[0][0] = sx;  f.basis[0][1] = 0.0; f.basis[0][2] = 0.0;
				f.basis[1][0] = 0.0; f.basis[1][1] = 1.0; f.basis[1][2] = 0.0;
				f.basis[2][0] = 0.0; f.basis[2][1] = 0.0; f.basis[2][2] = sz;

				frames.push_back(std::move(f));
			}

			return frames;
		}

		//============================================================================
		// 1) filename contains "_X" or "_x" before the extension, or "_L"/"_M"/"_H"
		//    followed by "_X"/"_x".
		// 2) If it's the last env in the .AI and has a body, check if the part's
		//    filename is a case-insensitive prefix of the body's filename.
		//============================================================================
		std::string model_variant(const std::string& filename) {
			std::string out;

			for(char c : filename) {

				if(c >= 'A' && c <= 'Z')
					out += (char)(c | 0x20);
				else if(c >= 'a' && c <= 'z')
					out += c;
				else
					break;

			}

			return out;
		}

		//============================================================================
		// Detect if an env part is an X-variant (destroyed) based on filename
		//============================================================================
		bool is_x_variant(
			const std::string& part_filename, 
			const std::string& body_filename, 
			bool is_last_in_env
		) {

			size_t dot = part_filename.find_last_of('.');
			std::string stem = (dot == std::string::npos) ? part_filename : part_filename.substr(0, dot);
			size_t underscore_pos = stem.find_last_of('_');

			if(underscore_pos != 0 && underscore_pos != std::string::npos) {
				char before = stem[underscore_pos - 1];

				if(before == 'X' || before == 'x')
					return true;

				if(underscore_pos + 2 < stem.size()) {
					char lod   = stem[underscore_pos + 1];
					char next_lod = stem[underscore_pos + 2];
					bool found_lod = (lod=='h' || lod=='H' || lod=='m' || lod=='M'
						           || lod=='l' || lod=='L' || lod=='u' || lod=='U' );

					if(found_lod && (next_lod == 'X' || next_lod == 'x'))
						return true;
				}
			}

			if(is_last_in_env && !body_filename.empty()) {
				std::string part_prefix = model_variant(part_filename);
				std::string body_prefix = model_variant(body_filename);

				if(!part_prefix.starts_with(body_prefix) && !body_prefix.starts_with(part_prefix))
					return true;

			}

			return false;
		}

		//============================================================================
		// Generate a key for caching based on the set of part filenames
		//============================================================================
		std::string parts_key(const std::vector<std::string>& ai_refs) {

			std::string key;
			key.reserve(ai_refs.size() * 16);

			for(const auto& ref : ai_refs) {
				key += io::to_lower(ref);
				key += '|';
			}

			return key;
		}

		//============================================================================
		// Remove duplicate part references while preserving order 
		//============================================================================
		std::vector<std::string> remove_duplicates(const std::vector<std::string>& ai_refs) {

			std::vector<std::string> out;
			std::set<std::string> existing;

			for(const auto& ref : ai_refs) {
				std::string lc = io::to_lower(ref);

				if(existing.insert(lc).second)
					out.push_back(ref);

			}

			return out;
		}

		//============================================================================
		// Build one model per-env
		//============================================================================
		int build_env_model(
			const std::string& model_stem,
			const std::string& folder_suffix,
			const std::vector<std::string>& ai_parts,
			const std::string& input_dir,
			const std::string& out_base,
			Version version,
			int ai_type,
			const PlotRoutine* c3g_routine,
			const model::ConvertOptions& opts
		) {

			std::string tag_label;

			if(folder_suffix.empty())
				tag_label = "base";
			else if(folder_suffix == "X")
				tag_label = "X";
			else if(folder_suffix.size() > 1 && folder_suffix[0] == 'X' && folder_suffix[1] == '_')
				tag_label = "X " + folder_suffix.substr(2);
			else if(folder_suffix[0] == '_')
				tag_label = folder_suffix.substr(1);
			else
				tag_label = folder_suffix;

			std::string env_dir = out_base + folder_suffix;
			io::make_dirs(env_dir);

			bool x_variant = (version == Version::Af3)
				&& !folder_suffix.empty() && folder_suffix[0] == 'X';

			std::vector<Part> parts = load_parts(input_dir, ai_parts, tag_label, opts);
			int active_parts = (int)std::ranges::count_if(parts, [](const Part& p) { return p.active; });

			if(active_parts == 0) {
				nlog::step("[%s] no parts loaded, skipping env\n", tag_label.c_str());
				return 2;
			}

			std::vector<AttachedPart> attached = (version == Version::C3g && c3g_routine)
				? resolve_attached_parts_c3g(parts, *c3g_routine)
				: resolve_attached_parts_af3(parts, ai_type, x_variant);

			EnvTextures env_tex = get_env_textures(parts, env_dir, opts);

			model::Model model;
			build_model(parts, attached, env_tex.tex_filename, model_stem, tag_label, model);

			model::ConvertOptions env_opts = opts;
			env_opts.out_dir = env_dir;

			writer::DebugOpts dbg;
			if(opts.debug)
				dbg.triads = build_part_frames(parts, attached);

			if(!writer::export_model(model, model_stem, env_opts, dbg))
				return 1;

			writer::debug::ModelInfo mi = writer::debug::measure(model);
			std::string env_rel = io::stem(env_dir);

			nlog::step("[%s] verts=%zu, tris=%zu, mats=%zu, textures=%d > %s\\\n",
				tag_label.c_str(), mi.position_count, mi.face_count,
				model.materials.size(), env_tex.found, env_rel.c_str());

			if(env_tex.missing > 0)
				nlog::info("       (%d missing textures)\n", env_tex.missing);

			return 0;
		}

		struct EnvModel {
			std::string folder_suffix;
			std::vector<std::string> parts;
		};

		struct EnvSplit {
			std::string              tag;
			std::vector<std::string> base;
			std::vector<std::string> x;
		};

		//============================================================================
		// Get one EnvModel per distinct part-set (base or X)
		//============================================================================
		void get_variant(
			const std::vector<EnvSplit>& splits, 
			bool use_base_parts, 
			const std::string& suffix_prefix, 
			std::vector<EnvModel>& plans
		) {

			std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string>>> groups;
			std::vector<std::string> envs_with_parts;

			for(const auto& env_split : splits) {
				const auto& split_parts = use_base_parts ? env_split.base : env_split.x;

				if(split_parts.empty())
					continue;

				envs_with_parts.push_back(env_split.tag);
				std::string split_key = parts_key(split_parts);
				auto it = groups.find(split_key);

				if(it == groups.end())
					groups[split_key] = { {env_split.tag}, split_parts };
				else
					it->second.first.push_back(env_split.tag);
			}

			bool single_group = (groups.size() == 1);

			for(auto& [key, value] : groups) {

				EnvModel plan;
				auto& [env_tags, plan_parts] = value;
				bool covers_all = (env_tags.size() == envs_with_parts.size());

				if(covers_all && single_group)
					plan.folder_suffix = suffix_prefix;
				else
					plan.folder_suffix = suffix_prefix + "_" + env_tags.front();

				plan.parts = plan_parts;
				plans.push_back(std::move(plan));
			}
		}

		//============================================================================
		// Build the EnvModel for all envs
		//=============================================================================
		std::vector<EnvModel> build_env(const ParsedAi& ai) {

			std::vector<EnvSplit> splits;
			splits.reserve(ai.envs.size());

			for(const auto& env : ai.envs) {

				EnvSplit env_split;
				env_split.tag = env.tag;

				auto unique = remove_duplicates(env.parts);
				const std::string body = unique.empty() ? std::string() : unique[0];

				for(size_t i = 0; i < unique.size(); ++i) {
					bool is_last = (i + 1 == unique.size());

					// X (destroyed) AF3 only
					if(ai.version == Version::Af3 && is_x_variant(unique[i], body, is_last))
						env_split.x.push_back(unique[i]);
					else
						env_split.base.push_back(unique[i]);
				}

				splits.push_back(std::move(env_split));
			}

			bool any_base = std::ranges::any_of(splits, [](const auto& env_split) {
				return !env_split.base.empty();
			});

			std::vector<EnvModel> plans;

			if(any_base) {
				get_variant(splits, true,  "",  plans);
				get_variant(splits, false, "X", plans);
			} else {
				get_variant(splits, false, "",  plans);
			}

			return plans;
		}

		//============================================================================
		// Trim whitespace, drop blank + pure-comment lines, strip trailing `; ...` tails. 
		// Return false for lines we should skip
		//============================================================================
		bool parse_ai_line(std::string_view line, std::string& out_line) {

			std::string parsed_line = io::trim(line);

			if(parsed_line.empty())
				return false;

			if(parsed_line[0] == ';')
				return false;

			if(size_t sc = parsed_line.find(';'); sc != std::string::npos)
				parsed_line = io::trim(parsed_line.substr(0, sc));

			if(parsed_line.empty())
				return false;

			out_line = std::move(parsed_line);
			return true;
		}

	}  // namespace

	//============================================================================
	// AF3 .AI file
	//   ;<comment>
	//   <type:int>
	//   >G | >D | >S | >N | >R | >B
	//     <part>.3do
	//     ...
	//   >IDOV
	//     <id>
	//   >DATA (not used)
	//   >LEAF
	//     <count>
	//============================================================================
	ParsedAi parse_ai_af3(const std::string& content) {
		ParsedAi ai = {};
		ai.version = Version::Af3;

		auto parse_int = [](std::string_view s, int& out) -> bool {
			auto [end, err] = std::from_chars(s.data(), s.data() + s.size(), out);
			return err == std::errc{} && end != s.data();
		};

		Section section = Section::None;
		int env_idx = -1;

		std::istringstream iss(content);
		std::string line;
		std::string parsed_line;

		while(std::getline(iss, line)) {

			if(!parse_ai_line(line, parsed_line))
				continue;

			if(parsed_line[0] == '>') {
				std::string tag = io::to_upper(parsed_line);

				if(tag == ">G" || tag == ">D" || tag == ">S" || tag == ">N" || tag == ">R" || tag == ">B") {
					ai.envs.push_back({tag.substr(1), {}});
					env_idx = (int)ai.envs.size() - 1;
					section = Section::Env;
				}
				else if(tag == ">IDOV")
					section = Section::Idov;
				else if(tag == ">LEAF")
					section = Section::Leaf;
				else
					section = Section::None; // includes >DATA and any unknown tag

				continue;
			}

			if(section == Section::None && ai.type == 0 && parse_int(parsed_line, ai.type))
				continue;

			switch(section) {
				case Section::Env:
					if(io::extension(parsed_line) == ".3do")
						ai.envs[env_idx].parts.push_back(parsed_line);
					break;
				case Section::Idov:
					if(ai.idov.empty())
						ai.idov = parsed_line;
					break;
				case Section::Leaf:
					if(ai.leaf == 0)
						parse_int(parsed_line, ai.leaf);
					break;
				default:
					break;
			}
		}

		return ai;
	}

	//============================================================================
	// C3G .AI file
	//   ;<comment>
	//   >g | >d | >s    (markers may appear consecutively)
	//     <part>.3do
	//     ...
	//   <
	//   <<              (separator: end of parts section, start of plot routines)
	//   <routine>,<base_part>,<cutoff> (plot routine line, one per LOD)
	//   <move_routine>    (not used)
	//   <
	//   <metadata fields> (not used)
	//============================================================================
	ParsedAi parse_ai_c3g(const std::string& content) {
		ParsedAi ai = {};
		ai.version = Version::C3g;

		auto parse_int = [](std::string_view s, int& out) -> bool {
			auto [end, err] = std::from_chars(s.data(), s.data() + s.size(), out);
			return err == std::errc{} && end != s.data();
		};

		std::vector<std::string> pending_envs;
		std::vector<std::string> pending_parts;

		auto flush = [&] {
			for(const auto& env : pending_envs) {
				for(auto& e : ai.envs) {

					if(e.tag == env) {
						e.parts.insert(e.parts.end(), pending_parts.begin(), pending_parts.end());
						break;
					}

				}
			}
			pending_envs.clear();
			pending_parts.clear();
		};

		Section section = Section::Env;   // env+parts grammar zone until `<<`

		std::istringstream iss(content);
		std::string line;
		std::string parsed_line;

		while(std::getline(iss, line)) {

			if(!parse_ai_line(line, parsed_line))
				continue;

			// `<<` ends the env+parts zone, opens the routines zone
			if(parsed_line == "<<") {
				flush();
				section = Section::Routines;
				continue;
			}

			// `<` terminates an env+parts group (env zone only)
			if(parsed_line == "<") {

				if(section == Section::Env)
					flush();
					
				continue;
			}

			if(section == Section::Env) {

				// Env marker
				if(parsed_line[0] == '>' && parsed_line.size() <= 4) {

					if(!pending_parts.empty())  // env after parts -> close current group
						flush();

					std::string env = io::to_upper(parsed_line.substr(1));
					pending_envs.push_back(env);

					// Add the env to ai.envs if not seen yet
					bool exists = false;
					for(const auto& e : ai.envs) {

						if(e.tag == env) { 
							exists = true; 
							break; 
						}

					}

					if(!exists)
						ai.envs.push_back({env, {}});

					continue;
				}

				// Part filename
				if(io::extension(parsed_line) == ".3do")
					pending_parts.push_back(parsed_line);

				continue;
			}

			if(section == Section::Routines && parsed_line.find(',') != std::string::npos) {

				std::vector<std::string> toks;
				std::string tok;
				std::istringstream lss(parsed_line);

				while(std::getline(lss, tok, ','))
					toks.push_back(io::trim(tok));

				if(toks.size() >= 2 && toks[0].size() == 4) {
					PlotRoutine routine;
					routine.name = io::to_lower(toks[0]);

					if(!parse_int(toks[1], routine.base_part))
						routine.base_part = 0;

					routine.cutoff = 0;

					if(toks.size() >= 3)
						parse_int(toks[2], routine.cutoff);

					ai.plot_routines.push_back(std::move(routine));
				}

				continue;
			}

			// First non-comma line in Routines is the move routine
			if(section == Section::Routines && parsed_line.size() == 4) {
				section = Section::Metadata;
				continue;
			}

			// Section::Metadata (not used)
		}

		flush();   // catch any unterminated parts at EOF

		return ai;
	}

	//============================================================================
	// Detect version by `<<` marker (C3G = present, AF3 = absent)
	//============================================================================
	ParsedAi parse_ai(const std::string& content) {

		if(content.find("<<") != std::string::npos)
			return parse_ai_c3g(content);
			
		return parse_ai_af3(content);
	}

	//============================================================================
	// Converter
	//============================================================================
	bool Converter::convert(const std::string& input_file, const model::ConvertOptions& opts) {

		auto file = io::read_file(input_file);

		if(!file) {
			nlog::error("cannot open '%s'", input_file.c_str());
			return false;
		}

		std::string content(reinterpret_cast<const char*>(file->data()), file->size());
		ParsedAi ai = parse_ai(content);

		std::string input_dir = io::dirname(input_file);
		std::string input_basename = input_file.substr(input_file.find_last_of("/\\") + 1);
		std::string model_stem = io::stem(input_file);

		const char* format_label = (ai.version == Version::C3g) ? "AI-C3G" : "AI-AF3";

		if(ai.version == Version::C3g) {
			std::string first_routine = ai.plot_routines.empty() ? std::string("?") : ai.plot_routines[0].name;

			nlog::announce(input_basename, format_label,
				std::format("model={}, envs={}, routines={}, top routine='{}'",
					model_stem, ai.envs.size(), ai.plot_routines.size(), first_routine));

		} else {
			std::string leaf_suffix = ai.leaf > 0 ? std::format(", LEAF={}", ai.leaf) : "";

			nlog::announce(input_basename, format_label,
				std::format("model={}, type={}, IDOV={}, envs={}{}",
					model_stem, ai.type, ai.idov.empty() ? "?" : ai.idov,
					ai.envs.size(), leaf_suffix));

		}

		if(ai.envs.empty()) {
			nlog::info(" (no env blocks)\n\n");
			return true;
		}

		if(ai.version == Version::C3g && ai.plot_routines.empty()) {
			nlog::info(" (no plot routines)\n\n");
			return true;
		}

		std::vector<EnvModel> plans = build_env(ai);
		if(plans.empty()) {
			nlog::info(" (no part lists)\n\n");
			return true;
		}

		const PlotRoutine* c3g_routine = (ai.version == Version::C3g && !ai.plot_routines.empty())
			? &ai.plot_routines.front()
			: nullptr;

		nlog::info(" dest=%s_*\\\n", opts.out_dir.c_str());

		int done = 0;
		for(const auto& plan : plans) {

			int rc = build_env_model(model_stem, plan.folder_suffix, plan.parts, input_dir, opts.out_dir, ai.version, ai.type, c3g_routine, opts);

			if(rc == 0)
				++done;

		}

		if(done == 0)
			nlog::info(" (all parts are empty)\n");

		nlog::info("\n");

		return true;
	}

}
